name: fit_app
description: A simple app for tracking gym time
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  flutter_speed_dial: ^5.0.0+1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  table_calendar: ^3.0.6
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - data/

